blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Join Slack
    url: "https://mirascope.com/slack-invite"
    about: Join the Mirascope Slack to ask questions, get help and chat about Mirascope
